#workspace = 1, name:web, monitor:HDMI-A-1
#workspace = name:code, 2, monitor:HDMI-A-1
#workspace = name:term, 3, monitor:HDMI-A-1
#workspace = name:web-dev, 4, monitor:DP-2
#workspace = name:media, 5, monitor:DP-2

